name: Hello World!

on: 
  push:
    branches:
      - main

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |  
          echo "Hello World !"
          
name: tell date

on: 
  push:
    branches:
      - main

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest
    steps:
      - name: tell date
        run: |  
          date

name: list directory!

on: 
  push:
    branches:
      - main

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest
    steps:
      - name: list directory
        run: |  
          ls -l
